### ISSUE TITLE
ModuleNotFoundError: No module named 'analysis'

### ISSUE THREAD

**Issue by schroedtert** [sainho93/jpsvis-online-ts#2]
When starting the server, following error occurs:
```
./src/server/server.py 
Traceback (most recent call last):
  File "./src/server/server.py", line 37, in <module>
    from analysis import _Plot_N_t
ModuleNotFoundError: No module named 'analysis'
```
Could resolve it locally by adding the absolute path to the analysis path to server.py:
```
sys.path.append("/home/development/jpsvis-online-ts/src/analysis")
```
But this destroys any portability.

**Comment by sainho93** [comment]
This bug is caused by sys path, fixed in commit af2b3ec5a7f435de43af289753b15726ebba2bb3
